In [35]:
#import numpy
import numpy as np

## Slicing arrays using start:stop:step notation

### 1D arrays

In [62]:
lstSSS = range(1, 21)
print(lstSSS)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]


In [67]:
print lstSSS[0:20:1]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]


In [66]:
print lstSSS[::1]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]


#### Index cannot be -ve but step size can be -ve

In [68]:
print lstSSS[0:20:-1]

[]


-1 indicates the index is reduced by 1 in each step, but when the beginning is smaller than the end index, it doesn't give any results.

In [78]:
print lstSSS[20:0:-1]

[20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2]


Value of the last element is missing.

#### Reverse the order of elements in a list

In [69]:
print lstSSS[::-1]

[20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


Ignoring the start and stop values and by just passing the step size, we can reverse the order of elements.

## 2D arrays

In [79]:
arrSSS = np.arange(1, 21).reshape((4, 5))
print arrSSS

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


### Reverse the order of elements in a row

In [80]:
print arrSSS[:,::-1]

[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]
 [20 19 18 17 16]]


### Reverse the order of elements in a col

In [82]:
print arrSSS[::-1,:]

[[16 17 18 19 20]
 [11 12 13 14 15]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]]


## 3D arrays

In [46]:
# initiate variables
block = 3
floor = 4
roomNo = 5

In [47]:
arr = np.arange(1, 61).reshape(block, floor, roomNo)

In [48]:
arr

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]],

       [[21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40]],

       [[41, 42, 43, 44, 45],
        [46, 47, 48, 49, 50],
        [51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60]]])

## Reverse the order of blocks

In [49]:
print(arr[::-1,:,:])

[[[41 42 43 44 45]
  [46 47 48 49 50]
  [51 52 53 54 55]
  [56 57 58 59 60]]

 [[21 22 23 24 25]
  [26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]]

 [[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]]


## Reverse the order of floor

In [42]:
print(arr[:,::-1,:])

[[[16 17 18 19 20]
  [11 12 13 14 15]
  [ 6  7  8  9 10]
  [ 1  2  3  4  5]]

 [[36 37 38 39 40]
  [31 32 33 34 35]
  [26 27 28 29 30]
  [21 22 23 24 25]]

 [[56 57 58 59 60]
  [51 52 53 54 55]
  [46 47 48 49 50]
  [41 42 43 44 45]]]


## Reverse the order of roomNo

In [50]:
print(arr[:,:,::-1])

[[[ 5  4  3  2  1]
  [10  9  8  7  6]
  [15 14 13 12 11]
  [20 19 18 17 16]]

 [[25 24 23 22 21]
  [30 29 28 27 26]
  [35 34 33 32 31]
  [40 39 38 37 36]]

 [[45 44 43 42 41]
  [50 49 48 47 46]
  [55 54 53 52 51]
  [60 59 58 57 56]]]
